### ISSUE TITLE
Lonely semicolon

### ISSUE THREAD

**Issue by tommythorn** [schoeberl/chisel-book#29]
There is a singular semicolon in the first Chisel example

https://github.com/schoeberl/chisel-book/blob/616ae0a8488050804fa8b099245d2647c6adcf6a/src/main/scala/Hello.scala#L24

Is this a typo?  Seems odd that this line needs one when the others don't.

**Comment by schoeberl** [comment]
This is just a typo. Some habit not so easy to kill from my C and Java years ;)
