### ISSUE TITLE
Broken link to test benches reference

### ISSUE THREAD

**Issue by IanBoyanZhang** [schoeberl/chisel-book#33]
https://github.com/schoeberl/chisel-book/blob/master/chisel-book.tex#L1339

Looks like link reference to [test benches](https://github.com/schoeberl/chisel-book/blob/master/chisel-book.tex#L1339) is out-of-date.

**Comment by schoeberl** [comment]
Are you proposing to use a newer version of ScalaTest? It is not broken, or is it?

This is about the ScalaTest version that Chisel 3.4.4 uses (3.0.8). It will be switched to 3.1.4 with Chisel 3.5. Then I should update that reference as well.

Thanks for pointing this out.

Martin

**Comment by IanBoyanZhang** [comment]
I would like to take the chance to express my gratitude. I just start learning chisel. I find your book is one of the most organized and updated studying materials available online. Thank you!

I meant the xilinx test benches reference doc url 
https://www.xilinx.com/support/documentation/sw_manuals/xilinx10/isehelp/ise_c_simulation_test_bench.htm
redirects to support doc homepage https://www.xilinx.com/support.html#documentation
either the original url has been moved or login required. 

Ian

**Comment by schoeberl** [comment]
Thanks, I've changed the link to a Wikipedia entry, although this is a very thin article.
