### ISSUE TITLE
reference to non-existing testing chapter

### ISSUE THREAD

**Issue by wunderabt** [schoeberl/chisel-book#36]
It looks like a chapter was removed but is still referenced:
https://github.com/schoeberl/chisel-book/blob/c467bfb3648dee1f964a71556eb1197ff5d5a29f/chisel-book.tex#L1249

**Comment by schoeberl** [comment]
Upps, you are so right! Bad that this actually made it into the Amazon printout of the 3rd edition. Maybe I should update it on Amazon?

Thanks,
Martin
